### ISSUE TITLE
Need more information

### ISSUE THREAD

**Issue by Merovex** [danielireson/github-wc-webhook#1]
Hey, I saw the underlying article and am interested in getting this to work. I write (crappy) novels. Would have liked to have seen "in action," and more importantly to know how you pull the data out and put into a graph, if you've done that.

**Comment by danielireson** [comment]
Hi Merovex, thanks for the feedback, in future articles i'll try and mention about how to expand on the project being discussed :).

This was only meant to be a basic project to compliment the article and as such it does what it says in the tin and nothing more - it counts the word commits in each git commit via a webhook. You have access to the `/commits` endpoint so you can extend as required. 

If you want graphs you'll have to look into:
1. Writing a script to convert the JSON from the `/commits` endpoint to a CSV friendly format so that you can then manually import that into Excel.
2. Adding another AWS Lambda endpoint that renders a web page with a collection of relevant JavaScript graphs. For this you might want to look into *Chart.js*.

My usage of the webhook was to create a [BitBar](https://getbitbar.com) that showed the total word count in my OSx menu bar. I did this in PHP by making a call to the `/commits` endpoint and just looking through the results.

```
<?php

$opts = [
    'http' => [
        'method' => 'GET',
        'header' => 'authorization: ez0598feec90fc7f273c944abe1b436bc8bb70b5'
    ]
];

$context = stream_context_create($opts);
$response = file_get_contents('https://vhnwjvrkr4.execute-api.eu-west-1.amazonaws.com/dev/commits', false, $context);
$commits = json_decode($response);

$total = 0;
foreach ($commits->commits as $commit) {
	$total += $commit->wordCount->net;
}

echo $total;
```

**Comment by danielireson** [comment]
I should probably also say that you should remember this word count is only ever an approximation as was discussed in the article. Whilst the discrepancies between the actual and reported word count will be manageable for smaller projects, as you're writing a novel you might not find it suitable as this will be out by a larger margin.
